### ISSUE TITLE
ie5 hack creating confusion

### ISSUE THREAD

**Issue by stoyan** [brettstimmerman/mensch#13]
```css
@media tty { 
  i{content:"\";/*" "*/}} a { color: black; } /*";}
}

a {color: white}
```

The hack itself is handled ok - two strings in the content property

The problem is that the next ruleset is considered part of the media block, while it should be outside of it

Test code:

```js
var mensch = require('mensch');
var css = require('fs').readFileSync('./examples/css.css').toString();
var parsed = mensch.parse(css);
var res = mensch.stringify(parsed, {indentation: '  '})

console.log(res)
```
Result:

```css
@media tty {
  i {
    content: "\";/*" "*/}} a { color: black; } /*";
  }

  a {
    color: white;
  }
}
```
