### ISSUE TITLE
empty value creating confusion

### ISSUE THREAD

**Issue by stoyan** [brettstimmerman/mensch#14]
in

```css
body {background:;}
#yo {display: block;}
```
Expected

```css
body {

}
#yo {
  display: block;
}
```

Actual

```css
body {
  background: ;#yo display: block;
}
```

AST
```json
{
  "type": "stylesheet",
  "stylesheet": {
    "rules": [
      {
        "type": "rule",
        "selectors": [
          "body"
        ],
        "declarations": [
          {
            "type": "property",
            "name": "background",
            "value": ";#yo display: block"
          }
        ]
      }
    ]
  }
}
```
