### ISSUE TITLE
Loose property spacing when value starts with "special/unexpected" chars '(@*/{):'.

### ISSUE THREAD

**Issue by bago** [brettstimmerman/mensch#21]
```css
body {
  background-color:( yellow;
  background-color:@ yellow;
  background-color:* yellow;
  background-color:/ yellow;
  background-color:{ yellow;
  background-color:) yellow;
  background-color:: yellow;
}
```

is parsed like this:
```css
body {
  background-color: (yellow;
  background-color: @yellow;
  background-color: *yellow;
  background-color: /yellow;
  background-color: {yellow;
  background-color: )yellow;
  background-color: :yellow;
}
```

Notice how the space after the special char and before "yellow" is lost by mensch. This is because the special char is added to the buffer but the state is never changed from before-value to value, so the next spaces are considered "something to be trimmed".
