### ISSUE TITLE
correct handling of escaped quotes

### ISSUE THREAD

**Issue by stoyan** [brettstimmerman/mensch#5]
this confuses the parser:

``` css
  .sele {
    content: "he\"lo";
  }
```

this is ok:

``` css
  .sele {
    content: "helo";
  }
```

``` json
{ type: 'property', 
  name: 'content', 
  value: '"helo"' }
```
