### ISSUE TITLE
new lines should be treated as spaces

### ISSUE THREAD

**Issue by stoyan** [brettstimmerman/mensch#8]
``` css
body
div
{color: red}
```

gives

``` js
{ type: 'rule',
  selectors: [ 'bodydiv' ],
  declarations: [ { type: 'property', name: 'color', value: 'red' } ] }
```

I think the selector should be `body div`
